{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyO8WxC1jdWRXZt+nnlcwIhQ"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","source":["#**Add python version you wish** to list\n","!sudo apt-get update -y\n","!sudo apt-get install python3.8\n","from IPython.display import clear_output\n","clear_output()\n","!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1\n","\n","# Choose one of the given alternatives:\n","!sudo update-alternatives --config python3\n","\n","# This one used to work but now NOT(for me)!\n","# !sudo update-alternatives --config python\n","\n","# Check the result\n","!python3 --version\n","\n","# Attention: Install pip (... needed!)\n","!sudo apt install python3-pip"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"zDuMiqRSmrOV","executionInfo":{"status":"ok","timestamp":1705548973242,"user_tz":360,"elapsed":8279,"user":{"displayName":"Jake Browning","userId":"02530641597246255144"}},"outputId":"b86c19d5-38b6-4645-b551-b602cb54ce5c"},"execution_count":11,"outputs":[{"output_type":"stream","name":"stdout","text":["update-alternatives: error: alternative path /usr/bin/python3.6 doesn't exist\n","There is only one alternative in link group python3 (providing /usr/bin/python3): /usr/bin/python3.8\n","Nothing to configure.\n","Python 3.8.18\n","Reading package lists... Done\n","Building dependency tree... Done\n","Reading state information... Done\n","python3-pip is already the newest version (22.0.2+dfsg-1ubuntu0.4).\n","0 upgraded, 0 newly installed, 0 to remove and 29 not upgraded.\n"]}]},{"cell_type":"code","source":["!python --version"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"ow_4JXrYo5Vk","executionInfo":{"status":"ok","timestamp":1705548983288,"user_tz":360,"elapsed":254,"user":{"displayName":"Jake Browning","userId":"02530641597246255144"}},"outputId":"efe64578-1f68-4c98-a369-b544fc6de825"},"execution_count":12,"outputs":[{"output_type":"stream","name":"stdout","text":["Python 3.8.18\n"]}]},{"cell_type":"code","source":["import sys\n","print(sys.version)"],"metadata":{"id":"K9RoXHdupIO-","executionInfo":{"status":"ok","timestamp":1705549012895,"user_tz":360,"elapsed":3,"user":{"displayName":"Jake Browning","userId":"02530641597246255144"}},"outputId":"39e4e763-b8df-4fbf-aed1-d00c5ccc190f","colab":{"base_uri":"https://localhost:8080/"}},"execution_count":13,"outputs":[{"output_type":"stream","name":"stdout","text":["3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]\n"]}]},{"cell_type":"code","source":["!sudo update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.6 1"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"WXF5DlJPmfcP","executionInfo":{"status":"ok","timestamp":1705548752942,"user_tz":360,"elapsed":252,"user":{"displayName":"Jake Browning","userId":"02530641597246255144"}},"outputId":"cf544ab1-fc9a-4cd2-cd1e-c654ebc51423"},"execution_count":8,"outputs":[{"output_type":"stream","name":"stdout","text":["update-alternatives: error: alternative path /usr/local/bin/python3.6 doesn't exist\n"]}]},{"cell_type":"code","execution_count":2,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"JI4cXsdZgZ2N","executionInfo":{"status":"ok","timestamp":1705547365909,"user_tz":360,"elapsed":2068,"user":{"displayName":"Jake Browning","userId":"02530641597246255144"}},"outputId":"65d167b6-76ae-4587-bd31-4ed147828753"},"outputs":[{"output_type":"stream","name":"stdout","text":["Cloning into 'RL4LMs'...\n","remote: Enumerating objects: 1095, done.\u001b[K\n","remote: Counting objects: 100% (446/446), done.\u001b[K\n","remote: Compressing objects: 100% (72/72), done.\u001b[K\n","remote: Total 1095 (delta 387), reused 374 (delta 374), pack-reused 649\u001b[K\n","Receiving objects: 100% (1095/1095), 29.84 MiB | 30.20 MiB/s, done.\n","Resolving deltas: 100% (696/696), done.\n"]}],"source":["# !git clone https://github.com/allenai/RL4LMs.git"]},{"cell_type":"code","source":["# !pip install -U pip setuptools wheel\n","# !pip install thinc\n","# !pip install spacy --no-build-isolation\n","# !pip install --upgrade cython\n","# !pip install -e RL4LMs/"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"1ba5mBm2i3VG","executionInfo":{"status":"ok","timestamp":1705548204279,"user_tz":360,"elapsed":61766,"user":{"displayName":"Jake Browning","userId":"02530641597246255144"}},"outputId":"4d30ae6f-e21f-45a9-f711-e4b85c2ddac1"},"execution_count":7,"outputs":[{"output_type":"stream","name":"stdout","text":["Requirement already satisfied: pip in /usr/local/lib/python3.10/dist-packages (23.3.2)\n","Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (69.0.3)\n","Requirement already satisfied: wheel in /usr/local/lib/python3.10/dist-packages (0.42.0)\n","\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n","\u001b[0mRequirement already satisfied: thinc in /usr/local/lib/python3.10/dist-packages (8.1.12)\n","Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc) (0.7.11)\n","Requirement already satisfied: murmurhash<1.1.0,>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from thinc) (1.0.10)\n","Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from thinc) (2.0.8)\n","Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from thinc) (3.0.9)\n","Requirement already satisfied: wasabi<1.2.0,>=0.8.1 in /usr/local/lib/python3.10/dist-packages (from thinc) (1.1.2)\n","Requirement already satisfied: srsly<3.0.0,>=2.4.0 in /usr/local/lib/python3.10/dist-packages (from thinc) (2.4.8)\n","Requirement already satisfied: catalogue<2.1.0,>=2.0.4 in /usr/local/lib/python3.10/dist-packages (from thinc) (2.0.10)\n","Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc) (0.1.4)\n","Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from thinc) (69.0.3)\n","Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from thinc) (1.10.13)\n","Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from thinc) (23.2)\n","Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.10/dist-packages (from thinc) (1.23.5)\n","Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->thinc) (4.5.0)\n","\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n","\u001b[0mRequirement already satisfied: spacy in /usr/local/lib/python3.10/dist-packages (3.6.1)\n","Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy) (3.0.12)\n","Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (1.0.5)\n","Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (1.0.10)\n","Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy) (2.0.8)\n","Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy) (3.0.9)\n","Requirement already satisfied: thinc<8.2.0,>=8.1.8 in /usr/local/lib/python3.10/dist-packages (from spacy) (8.1.12)\n","Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy) (1.1.2)\n","Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy) (2.4.8)\n","Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy) (2.0.10)\n","Requirement already satisfied: typer<0.10.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (0.9.0)\n","Requirement already satisfied: pathy>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (0.10.3)\n","Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from spacy) (6.4.0)\n","Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (4.66.1)\n","Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (1.23.5)\n","Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (2.31.0)\n","Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy) (1.10.13)\n","Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy) (3.1.3)\n","Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy) (69.0.3)\n","Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (23.2)\n","Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (3.3.0)\n","Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.5.0)\n","Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.3.2)\n","Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.6)\n","Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.7)\n","Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2023.11.17)\n","Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.2.0,>=8.1.8->spacy) (0.7.11)\n","Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.2.0,>=8.1.8->spacy) (0.1.4)\n","Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.10/dist-packages (from typer<0.10.0,>=0.3.0->spacy) (8.1.7)\n","Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy) (2.1.3)\n","\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n","\u001b[0mRequirement already satisfied: cython in /usr/local/lib/python3.10/dist-packages (3.0.8)\n","\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n","\u001b[0mObtaining file:///content/RL4LMs\n","  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n","Collecting BLEURT@ git+https://github.com/google-research/bleurt.git@c6f2375c7c178e1480840cf27cb9e2af851394f9 (from rl4lms==0.2.2)\n","  Cloning https://github.com/google-research/bleurt.git (to revision c6f2375c7c178e1480840cf27cb9e2af851394f9) to /tmp/pip-install-a1_v00gh/bleurt_f080edf9f56640eeaad27308237f2d64\n","  Running command git clone --filter=blob:none --quiet https://github.com/google-research/bleurt.git /tmp/pip-install-a1_v00gh/bleurt_f080edf9f56640eeaad27308237f2d64\n","  Running command git rev-parse -q --verify 'sha^c6f2375c7c178e1480840cf27cb9e2af851394f9'\n","  Running command git fetch -q https://github.com/google-research/bleurt.git c6f2375c7c178e1480840cf27cb9e2af851394f9\n","  Running command git checkout -q c6f2375c7c178e1480840cf27cb9e2af851394f9\n","  Resolved https://github.com/google-research/bleurt.git to commit c6f2375c7c178e1480840cf27cb9e2af851394f9\n","  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n","Collecting gem-metrics@ git+https://github.com/GEM-benchmark/GEM-metrics.git@431a8174bd6b3637e8d6118bfad2983e39e99733 (from rl4lms==0.2.2)\n","  Cloning https://github.com/GEM-benchmark/GEM-metrics.git (to revision 431a8174bd6b3637e8d6118bfad2983e39e99733) to /tmp/pip-install-a1_v00gh/gem-metrics_d69b5088ac334733913086e3770c0972\n","  Running command git clone --filter=blob:none --quiet https://github.com/GEM-benchmark/GEM-metrics.git /tmp/pip-install-a1_v00gh/gem-metrics_d69b5088ac334733913086e3770c0972\n","  Running command git rev-parse -q --verify 'sha^431a8174bd6b3637e8d6118bfad2983e39e99733'\n","  Running command git fetch -q https://github.com/GEM-benchmark/GEM-metrics.git 431a8174bd6b3637e8d6118bfad2983e39e99733\n","  Running command git checkout -q 431a8174bd6b3637e8d6118bfad2983e39e99733\n","  Resolved https://github.com/GEM-benchmark/GEM-metrics.git to commit 431a8174bd6b3637e8d6118bfad2983e39e99733\n","  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n","Collecting importlib-metadata<5.0 (from rl4lms==0.2.2)\n","  Using cached importlib_metadata-4.13.0-py3-none-any.whl (23 kB)\n","Collecting spacy==3.0.6 (from rl4lms==0.2.2)\n","  Using cached spacy-3.0.6.tar.gz (7.1 MB)\n","  Installing build dependencies ... \u001b[?25l\u001b[?25hdone\n","  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n","  \n","  \u001b[31m×\u001b[0m \u001b[32mGetting requirements to build wheel\u001b[0m did not run successfully.\n","  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n","  \u001b[31m╰─>\u001b[0m See above for output.\n","  \n","  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n","  Getting requirements to build wheel ... \u001b[?25l\u001b[?25herror\n","\u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n","\n","\u001b[31m×\u001b[0m \u001b[32mGetting requirements to build wheel\u001b[0m did not run successfully.\n","\u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n","\u001b[31m╰─>\u001b[0m See above for output.\n","\n","\u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n"]}]},{"cell_type":"code","source":[],"metadata":{"id":"wRL4GQ3Li7px"},"execution_count":null,"outputs":[]}]}